language: java

jdk:
  - openjdk11

services:
  - docker

script:
  - ./gradlew build
  - docker build . -t user
  - docker tag user corefantasy/user

deploy:
  provider: script
  script: bash dockerPush.sh
  on:
    branch: master
