---
micronaut:
    application:
        name: user
    server:
        port: 8080
    endpoints:
        info:
            enabled: True
            sensitive: False
---
datasources:
    default:
        url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
        username: ${JDBC_USER:sa}
        password: ${JDBC_PASSWORD:""}
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}
---
jpa:
    default:
        packages-to-scan:
            - 'com.corefantasy.user.model'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
---
core-fantasy:
    user:
        jwt-secret: "${CORE_FANTASY_JWT_SECRET}"
